# Here lie dragons!
#
# Note that there is no artifact step in this script. We do not want Paperclip
# jars to be built for every push & PR; our CI handles pushes to branches, while
# PRs can themselves link to Paperclip jars if it is necessary. Official such
# PRs will take use of testing builds.

name: Build Paper with sand duping then release it
on: [push]

jobs:
    build:
        # Only run on PRs if the source branch is on someone else's repo
        if: ${{ github.event_name == 'push'}}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [17]
            fail-fast: true
        steps:
            - uses: actions/checkout@v2.4.0
            - name: JDK ${{ matrix.java }}
              uses: actions/setup-java@v3.1.0
              with:
                  java-version: ${{ matrix.java }}
                  cache: 'gradle'
                  distribution: 'temurin'
            - name: Remove Fix for Sand duping
              run: |
                  PATCH=$(echo patches/server/$(ls patches/server/|grep Fix-sand-duping))
                  echo "Located patch for sand duping:" $PATCH
                  mv $PATCH patches/removed/
            - name: Patch and build
              run: |
                  git config --global user.email "no-reply@github.com"
                  git config --global user.name "Github Actions"
                  ./gradlew applyPatches --stacktrace
                  ./gradlew createReobfBundlerJar --stacktrace
                  cp ./build/libs/*.jar ./paper.jar
                  cat ./paper.jar | sha256sum
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1.1.4
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.run_number }}
                  release_name: Release ${{ github.run_number }}
                  draft: false
                  prerelease: false
            - name: Upload Jar
              id: upload-jar
              uses: actions/upload-release-asset@v1.0.2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./paper.jar
                  asset_name: paper.jar
                  asset_content_type:  application/java-archive
